// ----- HOUSES ------ // 
###
// GET ONE HOUSE BY ID. 
GET http://localhost:3002/api/houses/5fec3fc46692fe1d076d5379

###
// GET ALL HOUSES. 
GET http://localhost:3002/api/houses

###
// CREATE A HOUSE. 
POST http://localhost:3002/api/newhouse
Content-Type: application/json

{
  "houseName": "Huset",
  "houseCategory": "Året runt",
  "houseSize": "300",
  "numberOfRooms": "12"

}

###
// DELETE HOUSE
DELETE http://localhost:3002/api/houses/5fec3fc46692fe1d076d5379

###
// UPDATE HOUSE
PUT   http://localhost:3002/api/houses/5fec43c4cceaaf1f07ed3268
Content-Type: application/json

{
 "houseName": "Sommarstugan i Blekinge",
  "houseCategory": "fritidsboende",
  "houseSize": "87",
  "numberOfRooms": "3",
  "rooms": ["5feb3656cbd090ff99f2c81c"]
  
}