
//ONE
GET http://localhost:3002/api/images/600006302c613a808d268039

###

//ALL
GET http://localhost:3002/api/images/

###

POST http://localhost:3002/api/images
Content-Type: multipart/form-data; boundary=FormDataRow

--FormDataRow
Content-Disposition: form-data; name="image"; filename="brown-brim.jpg"
Content-Type: image/jpg

< ./polka-dot-shirt.jpg
--FormDataRow--

### Tänk på följande:
### ALLA boundary's måste BÖRJA med --
### SISTA boundary'n måste AVSLUTAS med --