// ----- PROJECT ------ // 
###
// GET ONE ITEM BY ID. 
GET http://localhost:3002/api/items/5fec4526996e81276488d087

###
// GET ALL ITEMS. 
GET http://localhost:3002/api/items

###
// CREATE AN ITEM. 
POST http://localhost:3002/api/newitem
Content-Type: application/json

{
  "itemName": "fönster",
  "imageId": "5ed612ec6aaf5cd950517f93",
  "description": "ipsum lorem lorem ipsum",
  "receipt": "5feb3656cbd090ff99f2c81c",
  "orderDate": "EL",
  "warranty": "3 år"
 
}

###
// DELETE ITEM
DELETE http://localhost:3002/api/items/5fec44a8996e81276488d086

###
// UPDATE ITEM
PUT   http://localhost:3002/api/items/5fec4526996e81276488d087
Content-Type: application/json

{
  "itemName": "dörr",
  "imageId": "5ed612ec6aaf5cd950517f93",
  "description": "ipsum lorem lorem ipsum",
  "receipt": "5feb3656cbd090ff99f2c81c",
  "orderDate": "2020-12-30",
  "warranty": "3 år" 
}