// ----- PROJECT ------ // 
###
// GET ONE PROJECT BY ID. 
GET http://localhost:3002/api/projects/5feb4415b86c74079a471b36

###
// GET ALL Projects. 
GET http://localhost:3002/api/projects

###
// CREATE A Project. 
POST http://localhost:3002/api/newproject
Content-Type: application/json

{
  "projectName": "Byte av pump",
  "imageId": "5ed612ec6aaf5cd950517f93",
  "description": "ipsum lorem lorem ipsum",
  "roomId": "5feb3656cbd090ff99f2c81c",
  "category": "EL"
 
}

###
// DELETE PROJECT
DELETE http://localhost:3002/api/projects/5feb44c48dd2ed082b67cfba

###
// UPDATE PROJECT
PUT   http://localhost:3002/api/projects/5feb44c48dd2ed082b67cfba
Content-Type: application/json

{
  "projectName": "Byte av däck",
  "imageId": "5ed612ec6aaf5cd950517f93",
  "description": "ipsum lorem lorem ipsum",
  "roomId": "5feb3656cbd090ff99f2c81c",
  "category": "EL"
}