// ----- USER ------ // 
###
// GET ONE USER BY ID. Is working!!!
GET http://localhost:3002/api/users/5feb090d6ce331ed6d5dc6a7

###
// GET ALL USERS. Is working!!!
GET http://localhost:3002/api/users


###
// CREATE A USER. Is working!!!
POST http://localhost:3002/api/newuser
Content-Type: application/json

{
  "firstName": "Filip",
  "lastName": "Svensson",
  "email": "dickssstehhdssssdnqvist@hotmail.com",
  "password": "4321"
}

###
// LOGIN Is working!!!
POST http://localhost:3002/api/users/login
Content-Type: application/json

{
  "email": "dickssstehhdssssdnqvist@hotmail.com",
  "password": "4321"
}

###
// DELETE USER Is working!!!
DELETE http://localhost:3002/api/users/5feb090d6ce331ed6d5dc6a7


###
// UPDATE USER Is working!!!
PUT   http://localhost:3002/api/users/5feb090d6ce331ed6d5dc6a7
Content-Type: application/json

{
  "phoneNumber": "07332332110",
  "address": "Skosnörstigen 6",
  "postCode": "1822282",
  "city": "Borås",
  "creditcardnumber": "688982722211117272"
}


